config/routes.rb
Rails.application.routes.draw do
  # telegram_webhooks TelegramWebhooksController

  # пользователи - регистрация
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  get 'users/:id/show', to: 'users#show', as: :user_show
  get 'users/:id/audit', to: 'users#audit', as: :user_audit

  # Визуальный редактор
  mount Ckeditor::Engine => '/ckeditor'
  # Коменатрии
  mount Commontator::Engine => '/commontator'

  # Страницы сайта
  resources :pages
  root "page#index"

  # Биржы криптовалют
  resources :markets, param: :slug do
    get 'go'
  end

  # Новости
  resources :news, param: :slug do
    get 'go', as: :go
  end


  get 'money/top/:type', to: 'money#top',  as: :money_top
  get 'money/:slug/mining', to: 'money#mining', as: :mining_money
  get 'money/:slug/events', to: 'money#events', as: :events_money
  get 'money/:slug/news', to: 'money#news', as: :news_money

  # Криптовалюты
  resources :money, param: :slug do
    resources :explorers, param: :explorer_slug
    resources :events, param: :event_slug
  end



  # Обменики криптовалют
  resources :exchanges, param: :slug do
    get 'go', param: :slug, as: :go_exchange
    get 'load_course', param: :slug
  end

  get 'change', to: 'change#change', as: :chenge_index
  get 'change/:currency_from/:money_from/:currency_to/:money_to', to: 'change#change', as: :chenge

  # Статьи / категории
  resources :articles, param: :slug
  resources :article_categories, param: :slug

  # Теги объектов
  get 'tags/:tag', to: 'articles#index', as: :tag

  # Пулы для майнинга
  resources :pools, param: :slug do
    get 'go'
    resources :moneys, controller: :pool_moneys do
      get 'go', as: :go
    end
  end

  # Оборудование для майнинга
  post 'miners/import', as: :import_miners, to: 'miners#import'
  get 'miners/import_nicehash', as: :import_nicehash_miners, to: 'miners#import_nicehash'
  resources :miners, param: :slug do
    resources :speeds, controller: :miner_speeds
    resources :modes, controller: :miner_modes, param: :slug
  end

  get 'algorithms/import', to: 'algorithms#import',  as: :algorithms_import
  resources :algorithms, param: :slug

  resources :socials, param: :slug do
    resources :youtube, controller: :youtube_chanels, param: :slug
    get 'youtube/:slug/youtube_update', to: 'youtube_chanels#update_from_youtube', as: :youtube_update
    get 'youtube/:slug/go', to: 'youtube_chanels#go', as: :go_youtube
    # get 'youtube/:slug', to: 'youtube_chanels#index', as: :youtube_chanels

    resources :telegram, controller: :telegram_chanels, param: :slug
    get 'telegram/:slug/go', to: 'telegram_chanels#go', as: :go_telegram
  end

  resources :go_counters

  resources :wallets, param: :slug do
    get 'go'
  end

  resources :news_sources

  authenticate :user, ->(u) { u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/news_source.rb
class NewsSource < ApplicationRecord
  scope :active, -> { where(status: 1) }

  audited
end

app/controllers/news_sources_controller.rb
class NewsSourcesController < ApplicationController
  before_action :set_news_source, only: [:show, :edit, :update, :destroy]

  # GET /news_sources
  def index
    authorize NewsSource
    @news_sources = NewsSource.all
  end

  # GET /news_sources/1
  def show
    authorize @news_source
  end

  # GET /news_sources/new
  def new
    authorize NewsSource
    @news_source = NewsSource.new
  end

  # GET /news_sources/1/edit
  def edit
    authorize @news_source
  end

  # POST /news_sources
  def create
    authorize NewsSource
    @news_source = NewsSource.new(news_source_params)

    if @news_source.save
      redirect_to @news_source, notice: 'News source was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /news_sources/1
  def update
    authorize @news_source
    if @news_source.update(news_source_params)
      redirect_to @news_source, notice: 'News source was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /news_sources/1
  def destroy
    authorize @news_source
    @news_source.destroy
    redirect_to news_sources_url, notice: 'News source was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news_source
      @news_source = NewsSource.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def news_source_params
      params.require(:news_source).permit(:name, :source, :website, :status)
    end
end

app/views/news_sources/_form.html.erb
<%= simple_form_for(@news_source) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :source %>
    <%= f.input :website %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/news_sources/_news_source.html.erb
<tr>
  <td><%= news_source.name %></td>
  <td><%= news_source.source %></td>
  <td><%= news_source.website %></td>
  <td><%= link_to 'Show', news_source %></td>
  <td>
    <% if policy(news_source).edit? %>
      <%= link_to t('systems.edit'), edit_news_source_path(news_source), class: 'btn btn-success btn-xs' %>
    <% end %>
  </td>
  <td>
    <% if policy(news_source).destroy? %>
      <%= link_to t('systems.destroy'), news_source, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
    <% end %>
  </td>
</tr>

app/views/news_sources/edit.html.erb
<h1>Editing News Source</h1>

<%= render 'form', news_source: @news_source %>

<%= link_to 'Show', @news_source %> |
<%= link_to 'Back', news_sources_path %>

app/views/news_sources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>News Sources</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Source</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render partial: 'news_sources/news_source', collection: @news_sources %>
  </tbody>
</table>

<br>

<%= link_to 'New News Source', new_news_source_path %>

app/views/news_sources/new.html.erb
<h1>New News Source</h1>

<%= render 'form', news_source: @news_source %>

<%= link_to 'Back', news_sources_path %>

app/views/news_sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @news_source.name %>
</p>

<p>
  <strong>Source:</strong>
  <%= @news_source.source %>
</p>

<p>
  <strong>Website:</strong>
  <%= @news_source.website %>
</p>

<%= link_to t('systems.edit'), edit_news_source_path(@news_source), class: 'btn btn-warning btn-xs' %> |
<%= link_to 'Back', news_sources_path %>