config/routes.rb
Rails.application.routes.draw do
  # telegram_webhooks TelegramWebhooksController

  # пользователи - регистрация
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  get 'users/:id/show', to: 'users#show', as: :user_show
  get 'users/:id/audit', to: 'users#audit', as: :user_audit

  # Визуальный редактор
  mount Ckeditor::Engine => '/ckeditor'
  # Коменатрии
  mount Commontator::Engine => '/commontator'

  # Страницы сайта
  resources :pages
  root "page#index"

  # Биржы криптовалют
  resources :markets, param: :slug do
    get 'go'
  end

  # Новости
  resources :news, param: :slug do
    get 'go', as: :go
  end


  get 'money/top/:type', to: 'money#top',  as: :money_top
  get 'money/:slug/mining', to: 'money#mining', as: :mining_money
  get 'money/:slug/events', to: 'money#events', as: :events_money
  get 'money/:slug/news', to: 'money#news', as: :news_money

  # Криптовалюты
  resources :money, param: :slug do
    resources :explorers, param: :explorer_slug
    resources :events, param: :event_slug
  end



  # Обменики криптовалют
  resources :exchanges, param: :slug do
    get 'go', param: :slug, as: :go_exchange
    get 'load_course', param: :slug
  end

  get 'change', to: 'change#change', as: :chenge_index
  get 'change/:currency_from/:money_from/:currency_to/:money_to', to: 'change#change', as: :chenge

  # Статьи / категории
  resources :articles, param: :slug
  resources :article_categories, param: :slug

  # Теги объектов
  get 'tags/:tag', to: 'articles#index', as: :tag

  # Пулы для майнинга
  resources :pools, param: :slug do
    get 'go'
    resources :moneys, controller: :pool_moneys do
      get 'go', as: :go
    end
  end

  # Оборудование для майнинга
  post 'miners/import', as: :import_miners, to: 'miners#import'
  get 'miners/import_nicehash', as: :import_nicehash_miners, to: 'miners#import_nicehash'
  resources :miners, param: :slug do
    resources :speeds, controller: :miner_speeds
    resources :modes, controller: :miner_modes, param: :slug
  end

  get 'algorithms/import', to: 'algorithms#import',  as: :algorithms_import
  resources :algorithms, param: :slug

  resources :socials, param: :slug do
    resources :youtube, controller: :youtube_chanels, param: :slug
    get 'youtube/:slug/youtube_update', to: 'youtube_chanels#update_from_youtube', as: :youtube_update
    get 'youtube/:slug/go', to: 'youtube_chanels#go', as: :go_youtube
    # get 'youtube/:slug', to: 'youtube_chanels#index', as: :youtube_chanels

    resources :telegram, controller: :telegram_chanels, param: :slug
    get 'telegram/:slug/go', to: 'telegram_chanels#go', as: :go_telegram
  end

  resources :go_counters

  resources :wallets, param: :slug do
    get 'go'
  end

  resources :news_sources

  authenticate :user, ->(u) { u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/news.rb
class News < ApplicationRecord
  scope :latest, -> (count = 5) { order(created_at: :desc).limit(count) }
  scope :published, -> { where(status: 7) }
  
  belongs_to :user
  before_validation :set_slug

  acts_as_taggable
  acts_as_commontable dependent: :destroy

  mount_uploader :image, NewsUploader

  validates :title, presence: true
  validates :slug, uniqueness: true

  def to_param
    slug
  end

  def all_comments
    parent_comments = Comment.where(:commentable_id => id)
    child_comments = Comment.where(:commentable_id => parent_comments.map(&:id))
    parent_comments + child_comments
  end

  private

  def set_slug
    self.slug = to_slug(self.title) if self.slug.blank?
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  before_action :set_breadcrumbs, only: [:show, :edit, :new]

  # GET /news
  def index
    @news = News.order(created_at: :desc).page params[:page]

    @page = set_meta(I18n.t('activerecord.models.news'))
  end


  def go
    @news = News.find_by(slug: params[:news_slug])
    if @news.link.present?
      redirect_to(@news.link)
    else
      redirect_to news_path(@news)
    end
  end

  # GET /news/1
  def show
    add_breadcrumb @news.title
    @meta_title = meta_title @news.title
    @meta_description = @news.meta_description
    @meta_keywors = @news.meta_keywors

    @og_properties = {
      title: @meta_title,
      type:  'article',
      image: view_context.image_url(@news.image),  # this file should exist in /app/assets/images/logo.png
      url: news_url(@news)
    }
  end

  # GET /news/new
  def new
    authorize News
    @news = News.new
    @news.user = current_user

    @h1 = I18n.t('breadcrumbs.create')
    add_breadcrumb I18n.t('breadcrumbs.homepage'), root_path
    add_breadcrumb I18n.t('activerecord.models.news'), news_index_path
    add_breadcrumb @h1
  end

  # GET /news/1/edit
  def edit
    authorize @news
    @news.user = current_user

    @h1 = I18n.t('breadcrumbs.update')
    add_breadcrumb I18n.t('breadcrumbs.homepage'), root_path
    add_breadcrumb I18n.t('activerecord.models.news'), news_index_path
    set_meta('{name}', @news)
    add_breadcrumb @h1
  end

  # POST /news
  def create
    authorize News
    @news = News.new(news_params)
    @news.user = current_user

    if @news.save
      redirect_to @news, notice: 'News was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /news/1
  def update
    authorize @news
    @news.user = current_user
    if @news.update(news_params)
      redirect_to @news, notice: 'News was successfully updated.'
    else
      add_breadcrumb @news.title, news_path(@news)
      add_breadcrumb I18n.t("breadcrumbs.update")
      render :edit
    end
  end

  # DELETE /news/1
  def destroy
    authorize @news
    News.destroy(@news.id)
    redirect_to news_index_url, notice: 'News was successfully destroyed.'
  end

  private
    def set_breadcrumbs
      add_breadcrumb I18n.t('breadcrumbs.homepage'), root_path
      add_breadcrumb I18n.t('activerecord.models.news'), news_index_path
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find_by(slug: params[:slug])
    end

    # Only allow a trusted parameter "white list" through.
    def news_params
      params.require(:news).permit(
        :title,
        :meta_description,
        :meta_keywors,
        :slug,
        :body,
        :source,
        :link,
        :tag_list,
        :image
      )
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_feed.html.erb
<div class="vertical-timeline-block">
  <div class="vertical-timeline-icon navy-bg">
    <i class="fa fa-briefcase"></i>
  </div>

  <div class="vertical-timeline-content">
    <h2><%= feed.title %></h2>
    <p>
      <%= feed.meta_description %>
    </p>

    <%= link_to t('.more_info'), feed, class: 'btn btn-sm btn-primary' %>

    <span class="vertical-date">
      <small></small>
      <small>
        <%= l feed.created_at, format: :short %>
      </small>
    </span>
  </div>
</div>

app/views/news/_form.html.erb
<%= simple_form_for(@news) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-md-6">
        <%= f.input :title %>
      </div>
      <div class="col-md-6">
        <%= f.input :slug %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= f.input :meta_description %>
      </div>
      <div class="col-md-6">
        <%= f.input :meta_keywors %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :image %>
      <p><%= image_tag(@news.image.thumb.url) if @news.image? %></p>
      <%= f.file_field :image %>
    </div>

    <%= f.cktext_area :body, class: 'someclass', ckeditor: { language: 'ru'} %>


    <div class="row">
      <div class="col-md-6">
        <%= f.input :source %>
      </div>
      <div class="col-md-6">
        <%= f.input :link %>
      </div>
    </div>

    <%= f.label :tag_list %><br/>
    <%= f.text_field :tag_list, class: 'tagsinput', value: f.object.tag_list.to_s %>
  </div>
  <br />
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/news/_news.html.erb
<div class="col-lg-12">
  <div class="ibox">
    <div class="ibox-content">
      <a href="<%= news_path(news) %>" class="btn-link">
        <h2>
          <%= news.title %>
        </h2>
      </a>
      <div class="small m-b-xs">
        <span class="text-muted">
          <i class="fa fa-clock-o"></i>
          <%= l news.created_at, format: :short %>
        </span>
      </div>
      <p>
        <%= news.meta_description %>
      </p>
      <div class="row">
        <div class="col-md-6">
          <h5>Tags:</h5>
          <% news.tag_list.each do |t| %>
            <button class="btn btn-primary btn-xs" type="button">
              <%= t %>
            </button>
          <% end %>
        </div>
        <div class="col-md-6">
          <div class="small text-right">
            <h5>Stats:</h5>
            <div><i class="fa fa-comments-o"> </i> <%= news.thread.filtered_comments.count.to_s %> comments</div>
            <i class="fa fa-eye"> </i> 0 views
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/news/edit.html.erb
<div class="wrapper wrapper-content">
  <%= render 'form', news: @news %>
</div>

app/views/news/index.html.erb
<div class="wrapper wrapper-content  animated fadeInRight blog">
  <% if policy(News).new? %>
      <%= link_to 'New News', new_news_path, class: 'btn btn-success' %>
  <% end %>
  <% if policy(NewsSource).index? %>
    <%= link_to 'News Source', news_sources_path, class: 'btn btn-success' %>
  <% end %>

  <% unless @page.body.nil? %>
    <%= @page.body.html_safe %>
  <% end %>

  <div class="row">
    <%= render partial: 'news/news', collection: @news %>
  </div>
  <%= paginate @news %>
</div>

app/views/news/new.html.erb
<div class="wrapper wrapper-content">
  <%= render 'form', news: @news %>
</div>

app/views/news/show.html.erb
<div class="wrapper wrapper-content animated fadeInRight article">
  <div class="row">
    <div class="col-lg-10 col-lg-offset-1">
      <div class="ibox">
        <div class="ibox-content">
          <div class="pull-right">
            <% if policy(@news).edit? %>
              <%= link_to t('systems.edit'), edit_news_path(@news), class: 'btn btn-warning btn-xs' %>
            <% end %>
            <% if policy(@news).destroy? %>
              <%= link_to t('systems.destroy'), @news, method: :delete, data: { confirm: t('systems.are_you_sure') } , class: 'btn btn-xs btn-danger' %>
            <% end %>
          </div>
          <div class="text-center article-title">
            <span class="text-muted"><i class="fa fa-clock-o"></i>
              <%= l @news.created_at, format: :short %>
            </span>
            <h1>
              <%= @news.title %>
            </h1>
          </div>
          <p style="overflow: hidden">
            <%= @news.body.html_safe unless @news.body.nil? %>
          </p>
          <%= link_to(
                t('.read_in_source'),
                news_go_path(@news),
                class: 'btn bth-default',
                target: '_blank'
              ) if @news.link.present? %>
          <hr>
          <div class="row">
            <div class="col-md-6">
              <h5>Tags:</h5>
              <% @news.tag_list.each do |t| %>
                  <button class="btn btn-primary btn-xs" type="button">
                    <%= t  %>
                  </button>
              <% end %>
            </div>
            <div class="col-md-6">
              <div class="small text-right">
                <h5>Stats:</h5>
                <div> <i class="fa fa-comments-o"> </i> <%= @news.thread.filtered_comments.count.to_s %> comments </div>
                <i class="fa fa-eye"> </i> 0 views
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-12">
              <%= commontator_thread(@news) %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>