config/routes.rb
Rails.application.routes.draw do
  # telegram_webhooks TelegramWebhooksController

  # пользователи - регистрация
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  get 'users/:id/show', to: 'users#show', as: :user_show
  get 'users/:id/audit', to: 'users#audit', as: :user_audit

  # Визуальный редактор
  mount Ckeditor::Engine => '/ckeditor'
  # Коменатрии
  mount Commontator::Engine => '/commontator'

  # Страницы сайта
  resources :pages
  root "page#index"

  # Биржы криптовалют
  resources :markets, param: :slug do
    get 'go'
  end

  # Новости
  resources :news, param: :slug do
    get 'go', as: :go
  end


  get 'money/top/:type', to: 'money#top',  as: :money_top
  get 'money/:slug/mining', to: 'money#mining', as: :mining_money
  get 'money/:slug/events', to: 'money#events', as: :events_money
  get 'money/:slug/news', to: 'money#news', as: :news_money

  # Криптовалюты
  resources :money, param: :slug do
    resources :explorers, param: :explorer_slug
    resources :events, param: :event_slug
  end



  # Обменики криптовалют
  resources :exchanges, param: :slug do
    get 'go', param: :slug, as: :go_exchange
    get 'load_course', param: :slug
  end

  get 'change', to: 'change#change', as: :chenge_index
  get 'change/:currency_from/:money_from/:currency_to/:money_to', to: 'change#change', as: :chenge

  # Статьи / категории
  resources :articles, param: :slug
  resources :article_categories, param: :slug

  # Теги объектов
  get 'tags/:tag', to: 'articles#index', as: :tag

  # Пулы для майнинга
  resources :pools, param: :slug do
    get 'go'
    resources :moneys, controller: :pool_moneys do
      get 'go', as: :go
    end
  end

  # Оборудование для майнинга
  post 'miners/import', as: :import_miners, to: 'miners#import'
  get 'miners/import_nicehash', as: :import_nicehash_miners, to: 'miners#import_nicehash'
  resources :miners, param: :slug do
    resources :speeds, controller: :miner_speeds
    resources :modes, controller: :miner_modes, param: :slug
  end

  get 'algorithms/import', to: 'algorithms#import',  as: :algorithms_import
  resources :algorithms, param: :slug

  resources :socials, param: :slug do
    resources :youtube, controller: :youtube_chanels, param: :slug
    get 'youtube/:slug/youtube_update', to: 'youtube_chanels#update_from_youtube', as: :youtube_update
    get 'youtube/:slug/go', to: 'youtube_chanels#go', as: :go_youtube
    # get 'youtube/:slug', to: 'youtube_chanels#index', as: :youtube_chanels

    resources :telegram, controller: :telegram_chanels, param: :slug
    get 'telegram/:slug/go', to: 'telegram_chanels#go', as: :go_telegram
  end

  resources :go_counters

  resources :wallets, param: :slug do
    get 'go'
  end

  resources :news_sources

  authenticate :user, ->(u) { u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  before_validation :set_slug

  validates :title, presence: true
  validates :slug, uniqueness: true

  audited

  def to_param
    slug
  end

  private

  def set_slug
    self.slug = to_slug(self.title) if self.slug.blank?
  end
end

app/controllers/article_categories_controller.rb
class ArticleCategoriesController < ApplicationController
  before_action :set_article_category, only: [:show, :edit, :update, :destroy]

  # GET /article_categories
  def index
    @article_categories = ArticleCategory.all
  end

  # GET /article_categories/1
  def show
    add_breadcrumb I18n.t('breadcrumbs.homepage'), root_path
    add_breadcrumb I18n.t('activerecord.models.article_category'), article_categories_path
    set_meta('{title}', @article_category)
  end

  # GET /article_categories/new
  def new
    authorize ArticleCategory
    @article_category = ArticleCategory.new

    @h1 = I18n.t('breadcrumbs.create')
    add_breadcrumb I18n.t('breadcrumbs.homepage'), root_path
    add_breadcrumb I18n.t('activerecord.models.article_category'), article_categories_path
    add_breadcrumb @h1
  end

  # GET /article_categories/1/edit
  def edit
    authorize @article_category
  end

  # POST /article_categories
  def create
    authorize ArticleCategory
    @article_category = ArticleCategory.new(article_category_params)

    if @article_category.save
      redirect_to @article_category, notice: 'Article category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /article_categories/1
  def update
    authorize @article_category
    if @article_category.update(article_category_params)
      redirect_to @article_category, notice: 'Article category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /article_categories/1
  def destroy
    authorize @article_category
    @article_category.destroy
    redirect_to article_categories_url, notice: 'Article category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article_category
      @article_category = ArticleCategory.find_by(slug: params[:slug])
    end

    # Only allow a trusted parameter "white list" through.
    def article_category_params
      params.require(:article_category).permit(:title, :body, :slug, :meta_desc, :meta_key, :image)
    end
end

app/helpers/article_categories_helper.rb
module ArticleCategoriesHelper
end

app/views/article_categories/_article_category.html.erb
<tr>
  <td><%= article_category.title %></td>
  <td><%= article_category.body %></td>
  <td><%= article_category.slug %></td>
  <td><%= article_category.meta_desc %></td>
  <td><%= article_category.meta_key %></td>
  <td><%= article_category.image %></td>
  <td><%= link_to 'Show', article_category %></td>
  <td>
    <% if policy(article_category).edit? %>
      <%= link_to t('systems.edit'), edit_article_category_path(article_category), class: 'btn btn-warning btn-xs' %>
    <% end %>
    <% if policy(article_category).destroy? %>
      <%= link_to t('systems.destroy'), article_category, method: :delete, data: {confirm: t('systems.are_you_sure')}, class: 'btn btn-xs btn-danger' %>
    <% end %>
  </td>
</tr>

app/views/article_categories/_form.html.erb
<%= simple_form_for(@article_category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.input :slug %>
    <%= f.input :meta_desc %>
    <%= f.input :meta_key %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/article_categories/edit.html.erb
<div class="wrapper wrapper-content">
  <%= render 'form', article_category: @article_category %>
</div>

app/views/article_categories/index.html.erb
<div class="wrapper wrapper-content">
  <table class="table">
    <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Slug</th>
      <th>Meta desc</th>
      <th>Meta key</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
      <%= render partial: 'article_categories/article_category', collection: @article_categories %>
    </tbody>
  </table>

  <br>

  <% if policy(ArticleCategory).new? %>
    <%= link_to 'New Article Category', new_article_category_path, class: 'btn btn-success' %>
  <% end %>
</div>

app/views/article_categories/new.html.erb
<div class="wrapper wrapper-content">
  <%= render 'form', article_category: @article_category %>
</div>

app/views/article_categories/show.html.erb
<div class="wrapper wrapper-content">
  <p>
    <strong>Title:</strong>
    <%= @article_category.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= @article_category.body %>
  </p>

  <p>
    <strong>Slug:</strong>
    <%= @article_category.slug %>
  </p>

  <p>
    <strong>Meta desc:</strong>
    <%= @article_category.meta_desc %>
  </p>

  <p>
    <strong>Meta key:</strong>
    <%= @article_category.meta_key %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= @article_category.image %>
  </p>
</div>