config/routes.rb
Rails.application.routes.draw do
  # telegram_webhooks TelegramWebhooksController

  # пользователи - регистрация
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  get 'users/:id/show', to: 'users#show', as: :user_show
  get 'users/:id/audit', to: 'users#audit', as: :user_audit

  # Визуальный редактор
  mount Ckeditor::Engine => '/ckeditor'
  # Коменатрии
  mount Commontator::Engine => '/commontator'

  # Страницы сайта
  resources :pages
  root "page#index"

  # Биржы криптовалют
  resources :markets, param: :slug do
    get 'go'
  end

  # Новости
  resources :news, param: :slug do
    get 'go', as: :go
  end


  get 'money/top/:type', to: 'money#top',  as: :money_top
  get 'money/:slug/mining', to: 'money#mining', as: :mining_money
  get 'money/:slug/events', to: 'money#events', as: :events_money
  get 'money/:slug/news', to: 'money#news', as: :news_money

  # Криптовалюты
  resources :money, param: :slug do
    resources :explorers, param: :explorer_slug
    resources :events, param: :event_slug
  end



  # Обменики криптовалют
  resources :exchanges, param: :slug do
    get 'go', param: :slug, as: :go_exchange
    get 'load_course', param: :slug
  end

  get 'change', to: 'change#change', as: :chenge_index
  get 'change/:currency_from/:money_from/:currency_to/:money_to', to: 'change#change', as: :chenge

  # Статьи / категории
  resources :articles, param: :slug
  resources :article_categories, param: :slug

  # Теги объектов
  get 'tags/:tag', to: 'articles#index', as: :tag

  # Пулы для майнинга
  resources :pools, param: :slug do
    get 'go'
    resources :moneys, controller: :pool_moneys do
      get 'go', as: :go
    end
  end

  # Оборудование для майнинга
  post 'miners/import', as: :import_miners, to: 'miners#import'
  get 'miners/import_nicehash', as: :import_nicehash_miners, to: 'miners#import_nicehash'
  resources :miners, param: :slug do
    resources :speeds, controller: :miner_speeds
    resources :modes, controller: :miner_modes, param: :slug
  end

  get 'algorithms/import', to: 'algorithms#import',  as: :algorithms_import
  resources :algorithms, param: :slug

  resources :socials, param: :slug do
    resources :youtube, controller: :youtube_chanels, param: :slug
    get 'youtube/:slug/youtube_update', to: 'youtube_chanels#update_from_youtube', as: :youtube_update
    get 'youtube/:slug/go', to: 'youtube_chanels#go', as: :go_youtube
    # get 'youtube/:slug', to: 'youtube_chanels#index', as: :youtube_chanels

    resources :telegram, controller: :telegram_chanels, param: :slug
    get 'telegram/:slug/go', to: 'telegram_chanels#go', as: :go_telegram
  end

  resources :go_counters

  resources :wallets, param: :slug do
    get 'go'
  end

  resources :news_sources

  authenticate :user, ->(u) { u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/youtube_chanel.rb
class YoutubeChanel < ApplicationRecord
  belongs_to :social

  before_validation :set_slug

  validates :slug, uniqueness: true

  def to_param
    slug
  end

  def go_commit(ip)
    GoCounter.create({
      resource_class: self.class,
      resource_id: self.id,
      date_go: Time.now,
      ip: ip
    })
  end

  def yt
    Yt::Channel.new id: self.chanel_id
  end

  audited

  private

  def set_slug
    self.slug = to_slug(self.name) if self.slug.blank?
  end
end

app/controllers/youtube_chanels_controller.rb
class YoutubeChanelsController < ApplicationController
  before_action :set_youtube_chanel, only: [:show, :edit, :update, :destroy, :update_from_youtube]
  before_action :set_social

  def go
    @youtube_chanels = YoutubeChanel.find_by(slug: params[:youtube_chanel_slug])
    if @youtube_chanels.partner_link.present?
      @youtube_chanels.go_commit(request.remote_ip)
      redirect_to(@youtube_chanels.partner_link)
    else
      if @youtube_chanels.website.present?
        @youtube_chanels.go_commit(request.remote_ip)
        redirect_to(@youtube_chanels.website)
      else
        redirect_to social_youtube_path(@youtube_chanels)
      end
    end
  end

  # GET /youtube_chanels
  def index
    @youtube_chanels = YoutubeChanel.page params[:page]

    add_breadcrumb I18n.t('breadcrumbs.homepage'), root_path
    set_meta(I18n.t('activerecord.models.youtube_chanels'))
    add_breadcrumb @h1
  end

  # GET /youtube_chanels/1
  def show
    add_breadcrumb I18n.t('breadcrumbs.homepage'), root_path
    add_breadcrumb I18n.t('activerecord.models.youtube_chanels'), social_youtube_index_path(@social)
    set_meta('{name}', @youtube_chanel)
    add_breadcrumb @h1
  end

  # GET /youtube_chanels/new
  def new
    authorize YoutubeChanel
    @youtube_chanel = YoutubeChanel.new
    @youtube_chanel.social = @social
    @h1 = I18n.t('breadcrumbs.create')
    add_breadcrumb I18n.t('breadcrumbs.homepage'), root_path
    add_breadcrumb I18n.t('activerecord.models.youtube_chanels'), social_youtube_index_path(@social)
    add_breadcrumb @h1
  end

  # GET /youtube_chanels/1/edit
  def update_from_youtube
    authorize @youtube_chanel

    channel = @youtube_chanel.yt

    @youtube_chanel.name = channel.title
    @youtube_chanel.image = channel.thumbnail_url(:high)
    @youtube_chanel.body = channel.description
    @youtube_chanel.count_user = channel.subscriber_count
    @youtube_chanel.slug = nil
    @youtube_chanel.save

    redirect_to @youtube_chanel, notice: 'Youtube updated.'
  end

  # GET /youtube_chanels/1/edit
  def edit
    authorize @youtube_chanel
    @youtube_chanel.social = @social
    @h1 = I18n.t('breadcrumbs.update')
    add_breadcrumb I18n.t('breadcrumbs.homepage'), root_path
    add_breadcrumb I18n.t('activerecord.models.youtube_chanels'), social_youtube_path(@social)
    set_meta('{name}', @youtube_chanel)
    add_breadcrumb @h1
  end

  # POST /youtube_chanels
  def create
    authorize YoutubeChanel
    @youtube_chanel = YoutubeChanel.new(youtube_chanel_params)
    @youtube_chanel.social = @social
    if @youtube_chanel.name.empty?
      @youtube_chanel.name = @youtube_chanel.chanel_id
    end
    if @youtube_chanel.website.nil? || @youtube_chanel.website.empty?
      @youtube_chanel.website = "https://www.youtube.com/channel/#{@youtube_chanel.chanel_id}"
    end

    if @youtube_chanel.save
      redirect_to social_youtube_path(@social, @youtube_chanel), notice: 'Youtube chanel was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /youtube_chanels/1
  def update
    authorize @youtube_chanel
    if @youtube_chanel.update(youtube_chanel_params)
      redirect_to social_youtube_path(@social, @youtube_chanel), notice: 'Youtube chanel was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /youtube_chanels/1
  def destroy
    authorize @youtube_chanel
    @youtube_chanel.destroy
    redirect_to social_url(@social), notice: 'Youtube chanel was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_youtube_chanel
    @youtube_chanel = YoutubeChanel.find_by(slug: params[:slug])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_social
    @social = Social.find_by(slug: params[:social_slug])
  end

  # Only allow a trusted parameter "white list" through.
  def youtube_chanel_params
    params.require(:youtube_chanel).permit(
      :name,
      :slug,
      :body,
      :website,
      :image,
      :count_user,
      :tag_list,
      :chanel_id,
      :partner_link
    )
  end
end

app/helpers/youtube_chanels_helper.rb
module YoutubeChanelsHelper
end

app/views/youtube_chanels/_form.html.erb
<%= simple_form_for(@youtube_chanel, url: social_youtube_index_path(@social)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-md-6">
        <%= f.input :name %>
      </div>
      <div class="col-md-6">
        <%= f.input :slug %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <%= f.input :website %>
      </div>
      <div class="col-md-6">
        <%= f.input :chanel_id %>
      </div>
    </div>

    <%= f.cktext_area :body, class: 'someclass', ckeditor: { language: 'ru'} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/youtube_chanels/_youtube_chanel.html.erb
<div class="col-md-4">
  <div class="contact-box">
    <a href="<%= social_youtube_url(youtube_chanel.social, youtube_chanel) %>">
      <div class="text-center">
        <img style="margin: 0 auto;" alt="image" class="img-circle m-t-xs img-responsive" src="<%= youtube_chanel.image %>">
        <h3><strong><%= youtube_chanel.name %></strong></h3>
        <p><i class="fa fa-users"></i> <%= youtube_chanel.count_user %></p>
        <div class="clearfix"></div>
      </div>
    </a>
  </div>
</div>

app/views/youtube_chanels/edit.html.erb
<div class="wrapper wrapper-content">
  <%= render 'form', youtube_chanel: @youtube_chanel %>
</div>

app/views/youtube_chanels/index.html.erb
<div class="wrapper wrapper-content">
  <div class="ibox float-e-margins">
    <div class="ibox-content">
      <div class="animated fadeInRight">
        <div class="row">
          <%= render partial: 'youtube_chanels/youtube_chanel',
                     collection: @youtube_chanels %>
        </div>
      </div>

      <%= paginate @youtube_chanels %>
    </div>
  </div>
  <% if policy(YoutubeChanel).new? %>
    <%= link_to t('socials.show.create_youtube_chanel'), new_youtube_chanel_path, class: 'btn btn-success' %>
  <% end %>
</div>

app/views/youtube_chanels/new.html.erb
<div class="wrapper wrapper-content">
  <%= render 'form', youtube_chanel: @youtube_chanel %>
</div>

app/views/youtube_chanels/show.html.erb
<div class="wrapper wrapper-content">
  <% if policy(@youtube_chanel).update_from_youtube? %>
    <%= link_to t('.update_from_youtube'),
                social_youtube_update_path(@youtube_chanel.social, @youtube_chanel),
                class: 'btn btn-primary btn-xs'
    %>
  <% end %>

  <% if policy(@youtube_chanel).edit? %>
    <%= link_to t('systems.edit'),
                edit_social_youtube_path(@youtube_chanel.social, @youtube_chanel),
                class: 'btn btn-success btn-xs'
    %>
  <% end %>

  <% if policy(@youtube_chanel).destroy? %>
    <%= link_to t('systems.destroy'),
                social_youtube_path(@youtube_chanel.social, @youtube_chanel),
                method: :delete,
                class: 'btn btn-danger btn-xs',
                data: { confirm: 'Are you sure?'}
    %>
  <% end %>

  <% if policy(@youtube_chanel).update_from_youtube? || policy(@youtube_chanel).edit? || policy(@youtube_chanel).destroy? %>
    <hr />
  <% end %>

  <div class="row">
    <div class="col-md-3">
      <%= image_tag @youtube_chanel.image if @youtube_chanel.image.present? %>
    </div>
    <div class="col-md-9">
      <p>
        <%= @youtube_chanel.body.html_safe %>
      </p>
      <p>
        <strong><%= t('.count_user') %>:</strong>
        <%= @youtube_chanel.count_user %>
      </p>
      <p>
        <%= link_to t('.go_to_channel'),
                    social_go_youtube_path(@youtube_chanel.social, @youtube_chanel),
                    class: 'btn btn-success',
                    target: '_blank'
        %>
      </p>
    </div>
  </div>

  <hr />
  <h3><%= t('.last_video_on_channel') %> <%= @youtube_chanel.name %></h3>
  <div class="row">
    <p>
      <% @youtube_chanel.yt.videos.first(9).each do |video| %>
        <iframe class="col-md-4"
                style="margin-bottom: 10px"
                height="315"
                src="https://www.youtube.com/embed/<%= video.id %>"
                frameborder="0"
                allow="autoplay; encrypted-media"
                allowfullscreen></iframe>
      <% end %>
    </p>
  </div>

  <p>
    <%= link_to t('.go_to_channel'),
                social_go_youtube_path(@youtube_chanel.social, @youtube_chanel),
                class: 'btn btn-success',
                target: '_blank'
    %>
  </p>

</div>